title = "Richard Standow"
baseURL = "https://richard.hitechmadeez.com/"
relativeURLs = true
uglyURLs = true
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = true
buildDrafts = false
defaultContentLanguage = "en"

[params]
address = "Portland, OR"
email = "rstandow+resume@gmail.com"
favicon = "img/favicon.png"
profileImage = "img/Richard Standow1.webp"
firstName = "Richard"
lastName = "Standow"
phone = "1-971-266-0167"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = true
showPublications = false
showQr = true
showSkills = true
showBlog = true

[params.google]

[params.google.analytics]
trackerID = "G-D5JB51QRGL"

[[params.handles]]
link = "https://www.linkedin.com/in/richard-standow-jr"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/rstandow"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"

# /admin/config.yml
#publish_mode = "editorial_workflow"